# Nombre del archivo: .github/workflows/security.yml
name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # Ejecutar diario a las 2 AM

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Run security audit
      run: dotnet list package --vulnerable --format json
      
    - name: CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        languages: csharp
        queries: security-and-quality
